#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Update the package list to make sure we have the latest information about available packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Ensure Nginx is running
sudo service nginx start

# Configure Nginx to listen on port 80 and return "Hello World!" at the root
echo "server {
    listen 80;
    server_name localhost;

    location / {
        echo 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
sudo service nginx restart
